# Generated by Django 5.2.14 on 2026-05-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=300, verbose_name='지원 메시지')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('accepted', '수락됨'), ('rejected', '거절됨'), ('cancelled', '지원취소')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '지원',
                'verbose_name_plural': '지원 목록',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('description', models.TextField(verbose_name='상세 설명')),
                ('location_sido', models.CharField(max_length=20, verbose_name='시/도')),
                ('location_sigungu', models.CharField(max_length=20, verbose_name='시/군/구')),
                ('location_dong', models.CharField(blank=True, max_length=30, verbose_name='동/읍/면')),
                ('location_detail', models.CharField(blank=True, max_length=100, verbose_name='상세 위치')),
                ('work_date', models.DateTimeField(verbose_name='근무 시작 일시')),
                ('work_hours', models.FloatField(verbose_name='근무 시간')),
                ('hourly_wage', models.IntegerField(verbose_name='시급 (원)')),
                ('status', models.CharField(choices=[('open', '모집중'), ('matched', '매칭완료'), ('closed', '마감'), ('cancelled', '취소')], default='open', max_length=20, verbose_name='상태')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '구인글',
                'verbose_name_plural': '구인글 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
