# Generated by Django 5.2.14 on 2026-05-17 06:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jobpost',
            name='jobs_jobpos_locatio_fb5ade_idx',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='location_detail',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='location_dong',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='location_sido',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='location_sigungu',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마감 일시'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='location',
            field=models.CharField(default='', max_length=200, verbose_name='장소'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='work_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='근무 종료 일시'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['closed_at'], name='jobs_jobpos_closed__64a68b_idx'),
        ),
    ]
