# Generated by Django 5.2.14 on 2026-05-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='비밀번호 찾기에 사용됩니다 (네이버 메일 권장)', max_length=254, null=True, unique=True, verbose_name='이메일'),
        ),
    ]
